// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB41iC28-k6ATK3F4xuxIkoB84hS0LK9Y',
    appId: '1:327897442929:web:618dadc21a88fc63dec9d0',
    messagingSenderId: '327897442929',
    projectId: 'pm-app-9252d',
    authDomain: 'pm-app-9252d.firebaseapp.com',
    storageBucket: 'pm-app-9252d.firebasestorage.app',
    measurementId: 'G-07QERHPKMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfFkHNkIzCTNNk-E4jd54jVkPIVzoVb2Q',
    appId: '1:327897442929:android:ec34fc57a3b2972fdec9d0',
    messagingSenderId: '327897442929',
    projectId: 'pm-app-9252d',
    storageBucket: 'pm-app-9252d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdYZ3hiWI0PgUvQA1n5-JDNcoi6ETa9TY',
    appId: '1:327897442929:ios:081dcad6ade1f8dadec9d0',
    messagingSenderId: '327897442929',
    projectId: 'pm-app-9252d',
    storageBucket: 'pm-app-9252d.firebasestorage.app',
    iosBundleId: 'com.example.pmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdYZ3hiWI0PgUvQA1n5-JDNcoi6ETa9TY',
    appId: '1:327897442929:ios:081dcad6ade1f8dadec9d0',
    messagingSenderId: '327897442929',
    projectId: 'pm-app-9252d',
    storageBucket: 'pm-app-9252d.firebasestorage.app',
    iosBundleId: 'com.example.pmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB41iC28-k6ATK3F4xuxIkoB84hS0LK9Y',
    appId: '1:327897442929:web:b0418f3d2747cef5dec9d0',
    messagingSenderId: '327897442929',
    projectId: 'pm-app-9252d',
    authDomain: 'pm-app-9252d.firebaseapp.com',
    storageBucket: 'pm-app-9252d.firebasestorage.app',
    measurementId: 'G-MHY74DCEV1',
  );
}
